language: node_js
dist: trusty
sudo: required
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
addons:
  chrome: stable
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start
install:
  - yarn
script:
after_success:
  - yarn run travis-deploy-once "yarn run release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
