language: node_js
dist: trusty
sudo: required
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
addons:
  chrome: stable
before_install:
install:
  - yarn
script:
after_success:
  - yarn run travis-deploy-once "npm run release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
